FROM --platform=linux/amd64  alpine:latest
FROM python:3.12.4

RUN mkdir /app
WORKDIR /app
COPY ../* /app
RUN pip3 install -r requirements.txt

EXPOSE 5000
CMD ["python", "panda-company-postgres.py"]
